sudo: false
language: ruby
cache: bundler
rvm:
  - 2.1.9
  - 2.2.5
  - 2.3.1
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
script:
  - bundle exec rake test
  - bundle exec rake package
  - gem install --local pkg/gem-compiler-*.gem
