language: ruby
before_script:
  - rake setup
  - gem install rake -v "~> 0.9.2.2"
  - gem install minitest -v "~> 3.2"
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
matrix:
  include:
    - rvm: 1.8.7
      env:
        matrix:
          - USE_RUBYGEMS="1.8.25"
          - USE_RUBYGEMS="2.0.3"
    - rvm: 1.9.3
      env:
        matrix:
          - USE_RUBYGEMS="1.8.25"
          - USE_RUBYGEMS="2.0.3"
