language: ruby
before_script:
  - rake setup
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - ruby-head
env:
  - USE_RUBYGEMS="1.8.25"
  - USE_RUBYGEMS="2.0.3"
  - USE_RUBYGEMS="2.2.2"
matrix:
  exclude:
    - rvm: 2.0.0
      env: USE_RUBYGEMS="1.8.25"
