---
version: "{build}"
skip_tags: true
clone_depth: 10

install:
  - ps: |
      $env:path = 'C:\Ruby' + $env:ruby_version + '\bin;' + $env:path
  - ruby --version
  - gem update --system --no-document
  - gem --version
  - ps: |
      if ((gem query -i bundler) -eq $False) {
        gem install bundler --no-document
      }
  - bundle install --jobs=3 --retry=3

test_script:
  - rake -rdevkit test
  - rake package
  - gem install --local pkg/gem-compiler-*.gem

build: off

environment:
  matrix:
    - ruby_version: "24"
    - ruby_version: "24-x64"
    - ruby_version: "23"
    - ruby_version: "23-x64"
    - ruby_version: "22"
    - ruby_version: "22-x64"
    - ruby_version: "21"
    - ruby_version: "21-x64"
