---
version: "{build}"
skip_tags: true
clone_depth: 10

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ruby --version
  - gem --version
  - gem install bundler --version "~> 1.11" --no-ri --no-rdoc
  - bundle install --jobs=3 --retry=3

test_script:
  - rake -rdevkit test
  - rake package
  - gem install --local pkg/gem-compiler-*.gem

build: off

environment:
  matrix:
    - ruby_version: "21"
    - ruby_version: "21-x64"
    - ruby_version: "22"
    - ruby_version: "22-x64"
    - ruby_version: "23"
    - ruby_version: "23-x64"
